Fix/cl vault unused funds
quasar-finance/quasar pull request #501
Opened 2023-09-16 02:56 UTC by njerschow

## 1. Overview

Changing the CL Vault contract to also use any funds that aren't being saved as rewards

## 2. Implementation details

Added a function that gets the usable balance of the contract

## 3. How to test/use

## 4. Checklist

- [ ] Does the Readme need to be updated?

## 5. Limitations (optional)

## 6. Future Work (optional)

2023-09-16 16:03 UTC, LaurensKubat requested changes
needs some minor changes then lgtm

2023-09-16 16:03 UTC, LaurensKubat commented on smart-contracts/contracts/cl-vault/src/helpers.rs
> +pub fn get_unused_balances(
This needs some tests

2023-09-16 16:03 UTC, LaurensKubat commented on smart-contracts/contracts/cl-vault/src/rewards/helpers.rs
> +    pub fn find_coin(&self, denom: String) -> Coin {
the `String` should be an `&str` here

2023-09-16 16:03 UTC, LaurensKubat commented on smart-contracts/contracts/cl-vault/src/vault/range.rs
> +    let unused_balances = get_unused_balances(deps.storage, &deps.querier, &env)?;
This needs to be tested, can be done by adding free balance to `test_execute_update_range`

2023-09-18 11:55 UTC, LaurensKubat submitted a review, later dismissed
lgtm

2023-09-18 13:09 UTC, LaurensKubat approved these changes
lgtm

2023-09-18 13:15 UTC, magiodev approved these changes
lgtm

2023-09-18 13:37 UTC, merged