Fix/init mint amount ref
quasar-finance/quasar pull request #546
Opened 2023-11-16 18:06 UTC by magiodev

## 1. Overview

## 2. Implementation details

## 3. How to test/use

## 4. Checklist

- [ ] Does the Readme need to be updated?

## 5. Limitations (optional)

## 6. Future Work (optional)

2023-11-17 12:17 UTC, ajansari95 submitted a review, later dismissed

2023-11-17 12:18 UTC, ajansari95 commented on smart-contracts/contracts/cl-vault/src/test_tube/proptest.rs
> +        //#[ignore]
```suggestion
        #[ignore]
```

2023-11-17 12:38 UTC, ajansari95 commented on smart-contracts/contracts/cl-vault/src/test_tube/proptest.rs
> +            let (app, contract_address, _cl_pool_id, admin_account) = init_test_contract( // TODO: evaluate using default_init() here
```suggestion
            let (app, contract_address, _cl_pool_id, admin_account) = init_test_contract( 
            // TODO: evaluate using default_init() here
```

2023-11-17 12:38 UTC, ajansari95 commented on smart-contracts/contracts/cl-vault/src/test_tube/range.rs
> +        let (app, contract, cl_pool_id, admin) = init_test_contract( // TODO: Evaluate creating a default_init() variant i.e. out_of_range_init()
```suggestion
        let (app, contract, cl_pool_id, admin) = init_test_contract( 
        // TODO: Evaluate creating a default_init() variant i.e. out_of_range_init()
```

2023-11-17 12:38 UTC, ajansari95 commented on smart-contracts/contracts/cl-vault/src/test_tube/range.rs
> +        let (app, contract, cl_pool_id, admin) = init_test_contract( // TODO: Evaluate creating a default_init() variant i.e. out_of_range_init()
```suggestion
        let (app, contract, cl_pool_id, admin) = init_test_contract( 
        // TODO: Evaluate creating a default_init() variant i.e. out_of_range_init()
```

2023-11-17 12:38 UTC, ajansari95 commented on smart-contracts/contracts/cl-vault/src/test_tube/range.rs
> +        let (app, _contract, _cl_pool_id, _admin) = init_test_contract( // TODO: Evaluate using default_init()
```suggestion
        let (app, _contract, _cl_pool_id, _admin) = init_test_contract( 
        // TODO: Evaluate using default_init()
```

2023-11-17 12:54 UTC, ajansari95 requested changes

2023-11-17 12:54 UTC, ajansari95 commented on smart-contracts/contracts/cl-vault/src/test_tube/proptest.rs
>          let balance = get_user_shares_balance(wasm, contract_address, account); // TODO: get user shares balance
```suggestion
        let balance = get_user_shares_balance(wasm, contract_address, account); 
        // TODO: get user shares balance
```

2023-11-17 12:54 UTC, ajansari95 commented on smart-contracts/contracts/cl-vault/src/test_tube/proptest.rs
>                  "./test-tube-build/wasm32-unknown-unknown/release/cl_vault.wasm",
```suggestion
                // TODO: evaluate using default_init() here
                "./test-tube-build/wasm32-unknown-unknown/release/cl_vault.wasm",
```

2023-11-17 13:47 UTC, ajansari95 submitted a review, later dismissed

2023-11-19 23:14 UTC, LaurensKubat approved these changes
lgtm, some good improvements in this pr for our overall code health too

2023-11-20 06:51 UTC, ajansari95 submitted a review, later dismissed
lgtm

2023-11-20 09:05 UTC, ajansari95 commented on smart-contracts/contracts/cl-vault/src/vault/admin.rs
> +    verify_tick_exp_cache(deps.storage)?;
remove this

2023-11-20 09:05 UTC, ajansari95 commented on smart-contracts/contracts/cl-vault/src/vault/admin.rs
> +        verify_tick_exp_cache(&mut deps.storage).unwrap();
can do here but in a assert operation to test

2023-11-20 09:15 UTC, ajansari95 approved these changes
lgtm

2023-11-20 09:59 UTC, ajansari95 approved these changes
lgtm 🚢

2023-11-20 10:08 UTC, LaurensKubat approved these changes
lgtm

2023-11-20 13:16 UTC, closed without merging