Replace checked_multiply_ratio with checked_mul_floor
quasar-finance/quasar pull request #747
Opened 2024-08-07 14:07 UTC by lubkoll

2024-08-07 16:58 UTC, arhamchordia requested changes
Checks are failing.

2024-08-08 13:19 UTC, ajansari95 approved these changes

2024-08-08 13:19 UTC, LaurensKubat submitted a review, later dismissed
lgtm

2024-08-08 13:23 UTC, ajansari95 approved these changes

2024-08-08 13:29 UTC, LaurensKubat approved these changes
lgtm

2024-08-08 14:08 UTC, arhamchordia approved these changes

2024-08-08 15:43 UTC, merged